version: '3.8'

services:
  frontend:
    build: ./front
    container_name: frontend_gallery
    ports:
      - ${FRONTEND_PORT}:3000
    networks:
      - red_gallery
    depends_on:
      - db
    environment:
      - NODE_ENV=production

  db:
    image: mysql:8.0
    container_name: mysql_gallery
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red_gallery

networks:
  red_gallery:
    name: red_gallery
    driver: bridge

volumes:
  db_data: 